export const FETCHING_USERS = 'FETCH_SMURFS';
export const FETCHING_SUCCESS = 'FETCH_SUCCESS';
export const FETCHING_FAILURE = 'FETCH_FAILURE';

export const ADDING_USERS = 'ADDING_SMURFS';
export const ADDING_SUCCESS = 'ADDING_SUCCESS';
export const ADDING_FAILURE = 'ADDING_FAILURE';

export const UPDATING_USERS = 'UPDATING_SMURFS';
export const UPDATING_SUCCESS = 'UPDATING_SUCCESS';
export const UPDATING_FAILURE = 'UPDATING_FAILURE';

export const DELETING_USERS = 'DELETING_SMURFS';
export const DELETING_SUCCESS = 'DELETING_SUCCESS';
export const DELETING_FAILURE = 'DELETING_FAILURE';